services:
  frontend:
    build: ./frontend  # 前端目录（包含修改后的代码）
    ports:
      - "8080:80"  # 前端通过 http://localhost 访问
    depends_on:
      - backend  # 后端启动后再启动前端
    networks:
      - app-network  # 加入同一网络

  backend:
    build: ./backend  # 后端目录
    # 无需暴露端口到宿主机，前端通过容器网络访问
    networks:
      - app-network

networks:
  app-network:
    driver: bridge  # 桥接网络，容器间可通过服务名通信